title: Hacker-Blog
description: "A Blog Following My InfoSec Journey"
author:
  name: "OffSecNewbie.com"
  email: "rowbot@offsecnewbie.com"
  url: "https://offsecnewbie.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "offsecnewbie.com"
year : "2020"
